<!-- 
Breadcrumb
Author: Marvin Manguiat
 Sourcefit Philippines Inc
 Sept 1, 2014
// -->
<section class="content-header">
             
                    <ol class="breadcrumb">
                        <?php
    // iterate through the pages
    foreach ($this->pages as $key => $page):
        ?>
        <li>
            <?php
            if($page->getLabel() === "Home"){
            	continue;
            }
            // if this isn't the last page, add a link and the separator
            if ($key < count($this->pages) - 1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
            <?php
            // otherwise, just output the name
            else:
            ?>
                <?php echo $page->getLabel(); ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
                    </ol>
 </section>
