
<?php
/**
 * Sidebar Content 
 * -Dynamic Sidebar for Zend Framework 2 
 * 
 * Author: Marvin Manguiat U.
 * Sourcefit Philippines Inc 
 * Aug. 28, 2014
 * 
 * 
 */
//var_dump($this->layout()->acl->isAllowed('admin','profile'));
$acl = $this->layout()->acl;
$role = $this->layout()->auth['role'];

?>

   
        <section class="sidebar">
        
          <div class="profile-container-main" style="background-color:#DD6D1C">
					<!-- Sidebar user panel -->
					<div class="user-panel">

						<div class="image" style="text-align: center;">
							<img src="<?php echo HOST. $this->layout()->auth["profile_pic_url"];?>" class="img-circle"
								alt="User Image"
								style="width: 80px; height: 85px; border: none; margin-bottom: 5px">
						</div>

						<div class="info">
							<p style="text-align: center">
								<span class="p_fname"><?php echo $this->layout()->auth["firstname"] ?></span><span class="p_lname"><?php echo $this->layout()->auth["lastname"] ?></span>
							</p>

							<p class="p_position">Manager</p>
							<small style="font-style: italic; color: #FCD0A6"><i
								class="fa  fa-quote-left"></i> Never gonna give you up Never
								gonna let you down Never gonna run around and desert you <i
								class="fa  fa-quote-right "></i> </small>
						</div>

					</div>
					</div>
					
     <?php foreach($this->container as $parent):?>
                      <?php if($parent->get('show_in_menu') === false) continue ?>
                       <?php if(!$parent->hasPages()):?>
                      <?php if($parent->get('resource')!="" && $acl->isAllowed($role,$parent->get('resource'))):?>
                        <li class="<?php echo $parent->isActive() ? "active":""?>">
                            <a href="<?php echo $parent->getHref();?>">
                                <i class="fa <?php echo $parent->get('class')?>"></i> 
                                <span><?php echo $parent->getLabel()?></span>
                               
                            </a>
                        </li>
                        <?php endif;?>
                        <?php endif;?>
                       <?php if($parent->hasPages()):?>
                        <?php if($parent->get('resource')!="" && $acl->isAllowed($role,$parent->get('resource'))):?>
                        <li class="treeview <?php echo $parent->isActive() ? "active":""?>">
                        
                            <a href="<?php echo $parent->getHref();?>">
                                <i class="fa <?php echo $parent->get('class')?>"></i>
                                <span><?php echo $parent->getLabel()?></span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            
                            <ul class="treeview-menu <?php echo $parent->isActive() ? "active":""?>">
                            <?php foreach ($parent as $child):?>
                            <?php if($child->get('resource')!="" && $acl->isAllowed($role,$child->get('resource'))):?>
                            <?php if($child->get('show_in_menu') === false) continue ?>
                            <li class="<?php echo $child->isActive() ? "active":"inactive"?>"><a href="<?php echo $child->getHref()?>"><i class="fa fa fa-stop"></i><?php echo $child->getLabel()?> </a></li>
                           <?php endif;?>
                            <?php endforeach;?>
                            </ul>
                        </li>
                        <?php endif;?>
                       <?php endif;?>
                     <?php endforeach;?>
                     
                     
                     
                     
                             </section>