<?php
$form = $this->form;
$form->setAttribute ( 'action', $this->url ( 'login/process', array (
		'action' => 'authenticate' 
) ) );
$form->prepare ();

?>
<!DOCTYPE html>
<html class="bg-black">
<head>
<meta charset="UTF-8">
<title>AdminLTE | Log in</title>
<meta
	content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
	name='viewport'>
<!-- bootstrap 3.0.2 -->
<link href="<?php echo HOST?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- font Awesome -->
<link href="<?php echo HOST?>/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="<?php echo HOST?>/css/AdminLTE.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOST?>/css/custom.css" rel="stylesheet" type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
</head>
<body class="bg-black skin-x">

	<div class="form-box" id="login-box">
	<?php echo $this->render('flashmessenger/layout') ?>
		<div class="header">Sign In</div>
		<?php echo $this->form()->openTag($form);?>
			<div class="body bg-gray">
				<div class="form-group">
					<?php  echo $this->formRow($form->get('username')); ?>
				</div>
				<div class="form-group">
						<?php  echo $this->formRow($form->get('password')); ?>
				</div>
				<div class="form-group">
					
					
				<?php  echo $this->formRow($form->get('remember_me')); ?>
				</div>
			</div>
			<div class="footer">
				      <?php   echo $this->formSubmit($form->get('submit')); ?>
				      <?php  echo $this->form()->closeTag();?>
				<p>
					<a href="#">I forgot my password</a>
				</p>

				<a href="register.html" class="text-center">Register a new
					membership</a>
			</div>


	</div>


	<!-- jQuery 2.0.2 -->
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
	<!-- Bootstrap -->
	<script src="<?php echo HOST?>/js/bootstrap.min.js" type="text/javascript"></script>

</body>
</html>