<?php

?>
<!DOCTYPE html>
<html class="bg-black">
<head>
<meta charset="UTF-8">
<title>AdminLTE | Log in</title>
<meta
	content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
	name='viewport'>
<!-- bootstrap 3.0.2 -->
<link href="<?php echo HOST?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- font Awesome -->
<link href="<?php echo HOST?>/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="<?php echo HOST?>/css/AdminLTE.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOST?>/css/custom.css" rel="stylesheet" type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
</head>
<body class="bg-black skin-x">

	<div class="form-box" id="login-box">
	<?php echo $this->render('flashmessenger/layout') ?>
		<div class="header">Register</div>
		
<form action="../../index.html" method="post">
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="Full name">
                    </div>
                    <div class="form-group">
                        <input type="text" name="userid" class="form-control" placeholder="User ID">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password2" class="form-control" placeholder="Retype password">
                    </div>
                </div>
                <div class="footer">                    

                    <button type="submit" class="btn bg-olive btn-block">Sign me up</button>

                    <a href="login.html" class="text-center">I already have a membership</a>
                </div>
            </form>


	</div>


	<!-- jQuery 2.0.2 -->
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
	<!-- jQuery UI 1.10.3 -->
	<script src="<?php echo HOST?>/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<!-- Bootstrap -->
	<script src="<?php echo HOST?>/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- jvectormap -->
	<script src="<?php echo HOST?>/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"
		type="text/javascript"></script>
	<script src="<?php echo HOST?>/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"
		type="text/javascript"></script>
	<!-- jQuery Knob Chart -->
	<script src="<?php echo HOST?>/js/plugins/jqueryKnob/jquery.knob.js"
		type="text/javascript"></script>
	<!-- daterangepicker -->
	<script src="<?php echo HOST?>/js/plugins/daterangepicker/daterangepicker.js"
		type="text/javascript"></script>
	<!-- datepicker -->
	<script src="<?php echo HOST?>/js/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- iCheck -->
	<script src="<?php echo HOST?>/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
	
	<!-- InputMask -->
    <script src="<?php echo HOST?>/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="<?php echo HOST?>/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="<?php echo HOST?>/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        
	<!-- AdminLTE App -->
	<script src="<?php echo HOST?>/js/AdminLTE/app.js" type="text/javascript"></script>

	<!-- AdminLTE dashboard demo (This is only for demo purposes) 
	<script src="<?php echo HOST?>/js/AdminLTE/dashboard.js" type="text/javascript"></script>-->

	<!-- AdminLTE for demo purposes 
	<script src="<?php echo HOST?>/js/AdminLTE/demo.js" type="text/javascript"></script>-->
	
	<!-- Custon Js -->
   <script src="<?php echo HOST?>/js/custom.js" type="text/javascript"></script>

</body>
</html>