<?php echo $this->render('flashmessenger/layout') ?>

<div class="row">
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->escapeHtml("My Staffs"); ?></div>
				<div class="panel-body">
					<div class="box-body">
						<!-- Content here -->
						<div class="box">
							<div class="box-header">
								<h3 class="box-title">Staffs Table</h3>
								<div class="box-tools">
									<div class="form-group">

										<div class="input-group input-sm pull-right">
											<select name="gender_id" class="form-control pull-right input-sm" style="width:80px;border-left:none;outline:none">
											    <option value="firstname">By Name</option>
												<option value="address">By Address</option>
												<option value="landline">By Landline</option>
												<option value="cellphone">By Landline</option>
											</select> 
											
											<input type="text" name="table_search"
												class="form-control input-sm pull-right"
												style="width:110px;" placeholder="Search" />
											<div class="input-group-btn">
												<button class="btn btn-sm btn-default">
													<i class="fa fa-search"></i>
												</button>
											</div>
										</div>

									</div>
								</div>
							</div>
							<!-- /.box-header -->
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover table-striped">
									<tr>
										<th></th>
										<th>Employee ID</th>
										<th>Full Name</th>
										<th>Date Hired</th>
										<th>Status</th>
										<th>Options</th>
									</tr>
									   <?php foreach ($this->paginator as $employee) : ?>
									   <?php 
									   //clean
									   $fname = ucfirst($this->escapeHtml($employee->firstname));
									   $lastname = ucfirst($this->escapeHtml($employee->lastname));
									   $middle = ucfirst($this->escapeHtml($employee->middle));
									   $address = $this->escapeHtml($employee->address);
									   $about = $this->escapeHtml($employee->about);
									   $birthdate = $this->escapeHtml($employee->birthdate);
									   $landline = $this->escapeHtml($employee->landline);
									   $cellphone = $this->escapeHtml($employee->cellphone);
									   
									   
									   if('1'==$employee->status){
									   	$htmlStatus = "<span class=\"label label-success\">Active</span>";
									   }else{
									   	$htmlStatus = "<span class=\"label label-danger\">Disabled</span>";
									   }?>
									
								<tr>
										<td>
											<div class="user-panel">
												<div class="pull-left image">
													<img src="<?php echo HOST.$this->escapeHtml($employee->profile_pic_url)?>" class="img-circle"
														alt="<?php echo $this->escapeHtml($employee->firstname)?>" title="<?php echo $this->escapeHtml($employee->firstname)?>">
												</div>

											</div>
										</td>
										<td><?php echo $this->escapeHtml($employee->id);?></td>
										<td><?php echo $fname." ".$lastname.". ".$middle?></td>
										<td><?php echo $employee->date_hired?></td>
										<td><?php echo $htmlStatus?></td>
										<td>
										<a
						href="<?php echo $this->url('hr',array('action'=>'view-employee','id'=>$employee->id)); ?>"><i class="fa fa-search"></i>View </a>
										</td>
									</tr>
                                      <?php endforeach;?>
								</table>
							</div>
							<br>
							
							<div class="box box-success" style="position: relative;">
                                <div class="box-header" style="cursor: move;">
                                    <i class="fa fa-comments-o"></i>
                                    <h3 class="box-title">Chat</h3>
                                    <div class="box-tools pull-right" data-toggle="tooltip" title="" data-original-title="Status">
                                        <div class="btn-group" data-toggle="btn-toggle">
                                            <button type="button" class="btn btn-default btn-sm active"><i class="fa fa-square text-green"></i></button>
                                            <button type="button" class="btn btn-default btn-sm"><i class="fa fa-square text-red"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 250px;"><div class="box-body chat" id="chat-box" style="overflow: hidden; width: auto; height: 250px;">
                                    <!-- chat item -->
                                    <div class="item">
                                        <img src="img/avatar.png" alt="user image" class="online">
                                        <p class="message">
                                            <a href="#" class="name">
                                                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 2:15</small>
                                                Mike Doe
                                            </a>
                                            I would like to meet you to discuss the latest news about
                                            the arrival of the new theme. They say it is going to be one the
                                            best themes on the market
                                        </p>
                                        <div class="attachment">
                                            <h4>Attachments:</h4>
                                            <p class="filename">
                                                Theme-thumbnail-image.jpg
                                            </p>
                                            <div class="pull-right">
                                                <button class="btn btn-primary btn-sm btn-flat">Open</button>
                                            </div>
                                        </div><!-- /.attachment -->
                                    </div><!-- /.item -->
                                    <!-- chat item -->
                                    <div class="item">
                                        <img src="img/avatar2.png" alt="user image" class="offline">
                                        <p class="message">
                                            <a href="#" class="name">
                                                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:15</small>
                                                Jane Doe
                                            </a>
                                            I would like to meet you to discuss the latest news about
                                            the arrival of the new theme. They say it is going to be one the
                                            best themes on the market
                                        </p>
                                    </div><!-- /.item -->
                                    <!-- chat item -->
                                    <div class="item">
                                        <img src="img/avatar3.png" alt="user image" class="offline">
                                        <p class="message">
                                            <a href="#" class="name">
                                                <small class="text-muted pull-right"><i class="fa fa-clock-o"></i> 5:30</small>
                                                Susan Doe
                                            </a>
                                            I would like to meet you to discuss the latest news about
                                            the arrival of the new theme. They say it is going to be one the
                                            best themes on the market
                                        </p>
                                    </div><!-- /.item -->
                                </div><div class="slimScrollBar" style="width: 7px; position: absolute; top: 65px; opacity: 0.4; display: none; border-radius: 0px; z-index: 99; right: 1px; height: 184.91124260355px; background: rgb(0, 0, 0);"></div><div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 0px; opacity: 0.2; z-index: 90; right: 1px; background: rgb(51, 51, 51);"></div></div><!-- /.chat -->
                                <div class="box-footer">
                                    <div class="input-group">
                                        <input class="form-control" placeholder="Type message...">
                                        <div class="input-group-btn">
                                            <button class="btn btn-success"><i class="fa fa-plus"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
							<!-- /.box-body -->
							

							
						</div>
						<!-- /.box -->


						<!-- Content here:end -->
					</div>
				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Client Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
               <?php echo $this->render('layout/client-menu') ?>
			</div>
		</div>
	</section>
</div>


