				<div class="panel panel-default sfit">
							<div class="panel-heading">
								<h3 class="panel-title">BULLETIN BOARD</h3>
							</div>
							<div class="panel-body navbar-custom-menu">
								<!-- / panel content -->

								<div class="news-box">
									<div class="box-body">
										<div class="panel-group" id="accordion">
											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
															Collapsible Group Item #1 
															<a class="accordion-toggle" data-toggle="collapse"
															data-parent="#accordion" href="#collapseOne">
															<i
															class="fa indicator fa-chevron-circle-down pull-right"></i>
															</a>
													</h4>
												</div>
												<!--  div id="collapseOne" class="panel-collapse collapse in" //-->
												<div id="collapseOne" class="panel-collapse collapse">
													<div class="panel-body">Anim pariatur cliche
														reprehenderit, enim eiusmod high life accusamus terry
														richardson ad squid. 3 wolf moon officia aute, non
														cupidatat skateboard dolor brunch. Food truck quinoa
														nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt
														aliqua put a bird on it squid single-origin coffee nulla
														assumenda shoreditch et. Nihil anim keffiyeh helvetica,
														craft beer labore wes anderson cred nesciunt sapiente ea
														proident. Ad vegan excepteur butcher vice lomo. Leggings
														occaecat craft beer farm-to-table, raw denim aesthetic
														synth nesciunt you probably haven't heard of them
														accusamus labore sustainable VHS.</div>
												</div>
											</div>
											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
															Collapsible Group Item #2 
															<a class="accordion-toggle" data-toggle="collapse"
															data-parent="#accordion" href="#collapseTwo"><i
															class="fa indicator fa-chevron-circle-down pull-right"></i>
															</a>
													</h4>
												</div>
												<div id="collapseTwo" class="panel-collapse collapse">
													<div class="panel-body">Anim pariatur cliche
														reprehenderit, enim eiusmod high life accusamus terry
														richardson ad squid. 3 wolf moon officia aute, non
														cupidatat skateboard dolor brunch. Food truck quinoa
														nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt
														aliqua put a bird on it squid single-origin coffee nulla
														assumenda shoreditch et. Nihil anim keffiyeh helvetica,
														craft beer labore wes anderson cred nesciunt sapiente ea
														proident. Ad vegan excepteur butcher vice lomo. Leggings
														occaecat craft beer farm-to-table, raw denim aesthetic
														synth nesciunt you probably haven't heard of them
														accusamus labore sustainable VHS.</div>
												</div>
											</div>
											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
														
															Collapsible Group Item #3 
															<a class="accordion-toggle" data-toggle="collapse"
															data-parent="#accordion" href="#collapseThree"><i
															class="fa indicator fa-chevron-circle-down  pull-right"></i>
															</a>
													</h4>
												</div>
												<div id="collapseThree" class="panel-collapse collapse">
													<div class="panel-body">Anim pariatur cliche
														reprehenderit, enim eiusmod high life accusamus terry
														richardson ad squid. 3 wolf moon officia aute, non
														cupidatat skateboard dolor brunch. Food truck quinoa
														nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt
														aliqua put a bird on it squid single-origin coffee nulla
														assumenda shoreditch et. Nihil anim keffiyeh helvetica,
														craft beer labore wes anderson cred nesciunt sapiente ea
														proident. Ad vegan excepteur butcher vice lomo. Leggings
														occaecat craft beer farm-to-table, raw denim aesthetic
														synth nesciunt you probably haven't heard of them
														accusamus labore sustainable VHS.</div>
												</div>
											</div>
										</div>

									</div>
									<div style="margin: 0 auto 0 auto">
										<small><a class="pull-right" href="#">View All</a></small>
									</div>
								</div>

							</div>
						</div>