


			  <ul>
			  

					<li><a href="#">Set Biometric Data</a></li>
					<li><a
						href="<?php echo $this->url('profile',array('action'=>'edit')); ?>">Activate Employee</a></li>
					<li><a
						href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Departments</a></li>

					<li><a
						href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

				</ul>
				
				