<?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'hr',
     array(
         'action' => 'view-employee',
         'id'     => $this->id,
     )
 ));
 
 $form->prepare();
//  $out= "";
 
//  $out.= $this->form()->openTag($form);
//  $out.= $this->formRow($form->get('users_id'));
//  $out.= $this->formRow($form->get('date_hired'));
//  $out.= $this->formRow($form->get('status'));
//  $out.= $this->formSubmit($form->get('submit'));
//  $out.= $this->form()->closeTag();
?>
<div class="well box-body">
	<div class="form-group">
        <?php echo $this->form()->openTag($form);?>
        <?php  echo $this->formHidden($form->get('users_id')); ?>
       
       <div class="form-group">
	    <div class="input-group">
           <?php  echo $this->formRow($form->get('date_hired')); ?>
         </div>
	   </div>
	   
	   <div class="form-group">
	    <div class="input-group">
           <?php echo  $this->formRow($form->get('status')); ?>
         </div>
	   </div>
	   
	    <div class="input-group">
                 <?php   echo $this->formSubmit($form->get('submit')); ?>
        </div>
                 
	   <?php echo $this->form()->closeTag();?>
	</div>
</div>
	
	
<ul>

	<li><i class="fa fa-paperclip"></i> <a href="<?php echo $this->url('hr',array('action'=>'employee-files','id'=>$this->id));?>">201 files</a> </li>
	<li><i class="fa fa-calendar"></i> <a href="<?php echo $this->url('hr',array('action'=>'employee-memo','id'=>$this->id)); ?>">Memos</a></li>
	<li><i class="fa fa-check-square"></i> <a href="#">Quizzes</a></li>
	<li><i class="fa fa-foursquare"></i> <a href="#">Attendance</a></li>
    <li><i class="fa fa-search"></i> <a href="#">Evaluations</a></li>
	<li><i class="fa fa-dollar"></i> <a href="#">Salary</a></li>
	<li><i class="fa fa-comments"></i> <a href="#">Feedback</a></li>
	<li><i class="fa fa-ticket"></i> <a href="#">Clubs</a></li>
	<li><i class="fa fa-bullseye"></i> <a href="#">Points</a></li>

	<li><i class="fa     fa-times-circle-o"></i> <a
		href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

</ul>