


<ul>

	<li><a href="#">201 Files</a></li>
	<li><a href="#">Memos</a></li>
	<li><a href="#">Quizzes</a></li>
	<li><a href="#">Attendance</a></li>
    <li><a href="#">Evaluations</a></li>
	<li><a href="#">Salary</a></li>
	<li><a href="#">Feedback</a></li>
	<li><a href="#">Clubs</a></li>
	<li><a href="#">Points</a></li>

	<li><a
		href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

</ul>

