  <?php echo $this->render('flashmessenger/layout');?>

<?php 


?>
<div style="margin-top: 0px;">

    <div class="well" style="text-align:center">
    <img src="<?php echo HOST.$this->employee_data['profile_pic_url']?>"
								alt="User Image" />
		
								
    <span class="label label-success">   <?php echo $this->layout()->position["position_name"] ?> </span>
     </div>	
  							
    
   
	<ul class="nav nav-pills nav-stacked">
		<li class="header"></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'view-employee','id'=>$this->id));?>"><i class="fa fa-user"></i>Overview</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-file','id'=>$this->id));?>"><i class="fa fa-pencil-square-o"></i>201 Files</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-memo','id'=>$this->id)); ?>"><i class="fa fa-calendar"></i>Memos</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-quizzes','id'=>$this->id))?>"><i class="fa fa-check-square"></i>Quizzes</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-attendance','id'=>$this->id));?>"><i class="fa fa-foursquare"></i>Attendance</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-evaluation','id'=>$this->id));?>"><i class="fa fa-search"></i>Evaluations</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-salary','id'=>$this->id));?>"><i class="fa fa-folder"></i>Salary</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-feedback','id'=>$this->id));?>"><i class="fa fa-folder"></i>Feedback</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-clubs','id'=>$this->id));?>"><i class="fa fa-folder"></i>Clubs</a></li>
		<li><a href="<?php echo $this->url('hr',array('action'=>'employee-points','id'=>$this->id));?>"><i class="fa fa-folder"></i>Points</a></li>
		<li><a href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>"><i class="fa fa-folder"></i>Logout</a></li>
	</ul>
	 
</div>
