						<div class="panel panel-default sfit">
							<div class="panel-heading">
								<h3 class="panel-title">NOTIFICATIONS</h3>
							</div>
							<div class="panel-body">

								<div class="news-box">
									<div class="box-body">
										<div class="news-list news-list-in-box">

											<div class="item">
												<div class="news-img">
													<img src="http://placehold.it/50x50/d2d6de/ffffff"
														alt="News Image" class="img-circle">
												</div>
												<div class="news-info">

													<p>
														<a href="#">Jose Morgan</a> and <a href="">Mark Scott</a>
														have birthday today!
													</p>

													<span class="news-description"> <small>Feb
															25, 2015</small>
													</span>

												</div>
											</div>
											<!-- /.item -->

											<div class="item">
												<div class="news-img">
													<img src="http://placehold.it/50x50/d2d6de/ffffff"
														alt="News Image" class="img-circle">
												</div>
												<div class="news-info">

													<p>
														<a href="#">Jose Morgan</a> and <a href="">Mark Scott</a>
														have birthday today!
													</p>

													<span class="news-description"> <small>Feb
															25, 2015</small>
													</span>

												</div>
											</div>
											<!-- /.item -->
											<div class="item">
												<div class="news-img">
													<img src="http://placehold.it/50x50/d2d6de/ffffff"
														alt="News Image" class="img-circle">
												</div>
												<div class="news-info">

													<p>
														<a href="#">Jose Morgan</a> and <a href="">Mark Scott</a>
														have birthday today!
													</p>

													<span class="news-description"> <small>Feb
															25, 2015</small>
													</span>

												</div>
											</div>
										</div>
									</div>

									<div style="margin: 0 auto 0 auto">
										<small><a class="pull-right" href="#">View All</a></small>
									</div>
								</div>



							</div>
						</div>