<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s style="display:none">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
     ->setMessageSeparatorString('</li><li>')
     ->setMessageCloseString('</li></ul></div>');
$out = "";
$out .= $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
$out .= $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
$out .= $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
$out .= $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

echo $out;
?>
