<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->escapeHtml("Change Password"); ?></div>
				<div class="panel-body">
					<div class="box-body">
						<!-- Content here -->

						<form  method="post" action="<?php $this->url("profile",array('action'=>'change-password'))?>">
							<div class="form-group">
								<label>Current Password</label> <input type="password" name="oldpassword" class="form-control"
									placeholder="Enter ...">
							</div>
							
							<div class="form-group">
								<label>New Password</label> <input type="password" name="newpassword1" class="form-control"
									placeholder="Enter ...">
							</div>
							
							<div class="form-group">
								<label>Re-type New Password</label> <input type="password" name="newpassword2" class="form-control"
									placeholder="Enter ...">
							</div>
							
							<div class="input-group">
                     <input type="submit" name="submit" id="profileSubmitbutton" class="btn btn-primary edt-profile-btn" value="Update">
                  </div>
						</form>

						<!-- Content here:end -->
					</div>
				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/profile-menu') ?>
			</div>
		</div>
	</section>
</div>

