<?php echo $this->render('flashmessenger/layout') ?>

<?php
// module/Album/view/album/album/edit.phtml:
$title = 'Edit Profile';
$this->headTitle ( $title );
?>

<?php
$form = $this->form;
$form->setAttribute ( 'action', $this->url ( 'profile', array (
		'action' => 'edit',
		'id' => $this->id 
) ) );

$form->prepare();

$date  =  new DateTime($form->get('birthdate')->getValue()) ;
$bdate =  $date->format('m/d/Y');
 ?>
 
 <div class="row">
 
 <!-- Left col -->
 <section class="col-lg-7 connectedSortable">
 <div>
 <!-- main sub page content// -->
 
 <div class="panel panel-default">
 <div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
<div class="panel-body">

	<div class="box-body">
	
			  <div class="form-group">
                 <?php echo $this->form()->openTag($form);?>
                  <?php  echo $this->formHidden($form->get('id')); ?>
                  <?php  echo $this->formHidden($form->get('users_id')); ?>
                   <div class="form-group">
                   <div class="input-group">
                  <?php  echo $this->formRow($form->get('firstname')); ?>
                  </div>
                  </div>
                  
                  <div class="form-group">
                  <div class="input-group">
                  <?php  echo $this->formRow($form->get('lastname')); ?>
                  </div>
                  </div>
                  
                  <div class="form-group">
                  <div class="input-group">
                  <?php  echo $this->formRow($form->get('middle')); ?>
                  </div>
                  </div>
                  
                  <div class="form-group">
                  <div class="input-group">
    
                    <?php  echo $this->formRow($form->get('birthdate')); ?>
                  
                   </div>
                  </div>
                  
                  <div class="form-group">
                   <div class="input-group">
                  <?php  echo $this->formRow($form->get('gender_id')); ?>
                   </div>
                  </div>
                  
                      <div class="form-group">
                     <div class="input-group">
                   <?php   echo $this->formRow($form->get('about')); ?>
                    </div>
                  </div>
                  
                          <div class="form-group">
                     <div class="input-group">
                  <?php  echo $this->formRow($form->get('address')); ?>
                          </div>
                  </div>
                              <!-- phone mask -->
                  <div class="form-group">
                     <div class="input-group">
                       <?php  echo $this->formRow($form->get('landline')); ?>
                     </div><!-- /.input group -->
                  </div><!-- /.form group -->
                  
                  <!-- phone mask -->
                  <div class="form-group">
                     <div class="input-group">
                   
                   <?php  echo $this->formRow($form->get('cellphone')); ?>
                      </div><!-- /.input group -->
                  </div><!-- /.form group -->
                
                 <div class="input-group">
                 <?php   echo $this->formSubmit($form->get('submit')); ?>
                 </div>
                  <?php  echo $this->form()->closeTag();?>
                   
             </div>

	</div>


</div>
</div>

</div>

</section>
<!-- /.Left col -->

<!-- right col (We are only adding the ID to make the widgets sortable)-->
<section class="col-lg-5 connectedSortable">

	<div class="panel panel-default">
		<div class="panel-heading">Profile Menu</div>
		<div class="panel-body rightbar-menu">
			<!-- right navigation //-->
           <?php echo $this->render('layout/menu') ?>
		</div>
	</div>
</section>
</div>        