

<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Settings</div>
				<div class="panel-body">

					<div class="box-body">
					
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
				<div class="panel-body rightbar-menu">
			<!-- right navigation //-->
			<ul>

				<li><a href="#">Change Profile Picture</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'edit')); ?>">Edit
						Profile Details</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Profile
						Settings</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Change
						Password</a></li>
				<li><a
					href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

			</ul>
		</div>
		</div>
	</section>

</div>