<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->profile['firstname'].", ".$this->profile['lastname']."  ".$this->profile['middle']."."?></div>
				<div class="panel-body">

					<div class="box-body">
						<dl class="dl-horizontal">
							<dt><?php echo $this->translate('Address')?>:</dt>
							<dd><?php echo $this->profile['address']?></dd>

							<dt><?php echo $this->translate('Landline')?>:</dt>
							<dd><?php echo $this->profile['landline']?></dd>

							<dt><?php echo $this->translate('Cellphone')?>:</dt>
							<dd><?php echo $this->profile['cellphone']?></dd>

							<dt><?php echo $this->translate('Joined Date')?>:</dt>
							<dd><?php echo $this->profile['created']?></dd>

							<dt><?php echo $this->translate('Last Update')?>:</dt>
							<dd><?php echo $this->profile['last_modified']?></dd>
							
						    <dt></dt>
							<dd></dd>

							<dt><?php echo $this->translate('About')?>:</dt>
							<dd><?php echo $this->profile['about']?></dd>
						</dl>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
			<div class="panel-body rightbar-menu">
			<!-- right navigation //-->
			<ul>

				<li><a href="#">Change Profile Picture</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'edit')); ?>">Edit
						Profile Details</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Profile
						Settings</a></li>
				<li><a
					href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Change
						Password</a></li>
				<li><a
					href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

			</ul>
		</div>
		</div>
	</section>

</div>