<?php echo $this->render('flashmessenger/layout')?>
<?php

$dt = new DateTime ();
?>


<!-- right col (We are only adding the ID to make the widgets sortable)-->
<section class="col-lg-5 connectedSortable">

	<h3>Notifications:</h3>
     
</section>


<div class="col-md-6">
	<div class="box box-solid" style="padding: 5px">

		<h1>Welcome <?php echo $this->layout()->auth["firstname"]?> <?php echo $this->layout()->auth["middle"]?> <?php echo $this->layout()->auth["lastname"]?></h1>
		<p>Welcome back to the wonderful world of Sourcefit!</p>

		<div class="well">
			<h4>Attendance for <?php echo $dt->format('l, M j, Y  (T) '); ?></h4>

			<div class="box">
				<p>Schedule</p>
			</div>
			<!--  buttons  -->
			<div class="row">

				<!-- ./col -->
				<div class="col-lg-3 col-xs-6">
					<p>Work</p>
					<div class="btn-group-vertical">
						<button type="button" class="btn btn-default">Work</button>
		
					</div>

				</div>

				<div class="col-lg-3 col-xs-6">
					<p>Non Work</p>

					<div class="btn-group-vertical" role="group-non-work"
						aria-label="...">
						<button type="button" class="btn btn-default">Break</button>
						<button type="button" class="btn btn-default">Other</button>
						
					</div>
				</div>

				<!-- ./col -->
				<div class="col-lg-3 col-xs-6">
					<div class="btn-group-vertical" role="group-non-work"
						aria-label="...">
						<button type="button" class="btn btn-default">End Shift</button>
					</div>
				</div>
				<!-- ./col -->
			</div>


		</div>


	</div>
</div>

<section class="col-lg-5 connectedSortable">
<div class="box" style="padding: 5px">
<h3>Whats New?</h3>

</div>
	
<div class="box" style="padding: 5px">
<h3>Question of the Day:</h3>
<p>How did you feel at the end of your work?</p>

</div>
</section>
