<?php echo $this->render('flashmessenger/layout') ?>
<?php
// module/Album/view/album/album/index.phtml:
$title = 'My albums';
$this->headTitle ( $title );
?>


<?php
$url = $this->url ( 'album', array (
		'action' => 'search' 
) );
?>


<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->escapeHtml($title); ?></div>
				<div class="panel-body">

					<div class="box-body">
						<form class="navbar-form navbar-left" role="search"
							action="<?php echo $url ?>" method="post">
							<div class="form-group">
								<input type="text" name="keyword" class="form-control"
									placeholder="Search">
							</div>
							<button type="submit" class="btn btn-default">Submit</button>
						</form>


						<table class="table">
							<tr>
								<th>Title</th>
								<th>Artist</th>
								<th>Category</th>
								<th>&nbsp;</th>
							</tr>
                          <?php foreach ($this->paginator as $album) : // <-- change here! ?>
                             <tr>
								<td><?php echo $this->escapeHtml($album->title);?></td>
								<td><?php echo $this->escapeHtml($album->artist);?></td>
								<td><?php echo $this->escapeHtml($album->category);?></td>
								<td><a
									href="<?php
					
					echo $this->url ( 'album', array (
							'action' => 'edit',
							'id' => $album->id 
					) );
					?>"
									class="btn btn-default">Edit</a> <a
									href="<?php
					
					echo $this->url ( 'album', array (
							'action' => 'delete',
							'id' => $album->id 
					) );
					?>"
									class="btn btn-default">Delete</a></td>
							</tr>
                    <?php endforeach; ?>
                        </table>

					</div>
					
					
					
					                        <?php
// add at the end of the file after the table
echo $this->paginationControl ( 
		// the paginator object
		$this->paginator, 
		// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
		'sliding', 
		// the partial to use to render the control
		array (
				'partial/paginator.phtml',
				'Album' 
		), 
		// the route to link to when a user clicks a control link
		array (
				'route' => 'album' 
		) );
?>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	 	<section class="col-lg-5 connectedSortable"> 

	 		<div class="panel panel-default"> 
	 			<div class="panel-heading">Album Menu</div> 
	 			<div class="panel-body"> 
	 				<ul class="navigation"> 

	 					<li><a href="#">Add New Album</a></li> 
	 					<li><a href="#">Settings</a></li> 
	 					<li><a href="#">Delete</a></li> 
	 					<li><a href="#">Logout</a></li> 

	 				</ul> 
	 			</div> 
	 		</div> 
	 	</section> 

</div>