<?php 
//Functions*****************

// function limitCharX($str,$limit=5)
// {
// 	if(strlen($str)<=$limit)
// 	{
// 		return $str;
// 	}
// 	else
// 	{
// 		$y=substr($str,0,$limit) . '...';
// 		return $y;
// 	}
// }

//array(15) { ["user_name"]=> string(13) "nivramstrikes" ["id"]=> string(1) "1" ["users_id"]=> string(1) "1" ["firstname"]=> string(5) "Paolo" ["lastname"]=> string(8) "Bideones" ["middle"]=> string(1) "C" ["birthdate"]=> string(10) "1895-07-01" ["gender_id"]=> string(1) "1" ["about"]=> string(365) "Bediones started his career as a commercial model, and later transitioned to television show hosting. He is best known for hosting GMA Network's Extra Challenge and Survivor Philippines.[1] He is now a TV host and the newest newscaster on TV5. On December 3, 2009, Bediones announced in a press conference that he had signed a three-year exclusive contract with TV5" ["address"]=> string(34) "Unit 1820 Makati Executive Tower 3" ["landline"]=> string(9) "122222222" ["cellphone"]=> string(9) "901223221" ["created"]=> string(10) "2014-09-02" ["profile_pic_url"]=> string(0) "" ["last_modified"]=> string(23) "Sep 02, 2014 @ 03:33 AM" }


$loggedInUser  = null;

// the user is not logged in, dislplay only the content,
// which is a sign in page
if(null===$this->layout()->auth){
	echo $this->content;
	return;
}

//var_dump($this->layout()->auth);

$loggedInUser = $this->layout()->auth["user_name"];

?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Sourcefit Management System | Dashboard</title>
<meta
	content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
	name='viewport'>
<link href="/css/custom.css" rel="stylesheet" type="text/css" />
<!-- bootstrap 3.0.2 -->
<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- font Awesome -->
<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Ionicons -->
<link href="/css/ionicons.min.css" rel="stylesheet" type="text/css" />
<!-- Morris chart -->
<link href="/css/morris/morris.css" rel="stylesheet" type="text/css" />
<!-- jvectormap -->
<link href="/css/jvectormap/jquery-jvectormap-1.2.2.css"
	rel="stylesheet" type="text/css" />
<!-- Date Picker -->
<link href="/css/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />
<!-- Daterange picker -->
<link href="/css/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<!-- bootstrap wysihtml5 - text editor -->
<link href="/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"
	rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond./js/1.3.0/respond.min.js"></script>
        <![endif]-->
</head>
<body class="skin-x">
	<!-- header logo: style can be found in header.less -->
	<header class="header">
        
        <?php  $url = $this->url('home');
         ?>
            <a href="<?php echo $url ?>" class="logo"> <!-- Add the class icon to your logo image or logo icon to add the margining -->
			Sourcefit Philippines
		</a>
		<!-- Header Navbar: style can be found in header.less -->
		<nav class="navbar navbar-static-top" role="navigation">
			<!-- Sidebar toggle button-->
			<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas"
				role="button"> <span class="sr-only">Toggle navigation</span> <span
				class="icon-bar"></span> <span class="icon-bar"></span> <span
				class="icon-bar"></span>
			</a>
			<div class="navbar-right">
				<ul class="nav navbar-nav">
					<!-- Messages: style can be found in dropdown.less-->
					<li class="dropdown messages-menu"><a href="#"
						class="dropdown-toggle" data-toggle="dropdown"> <i
							class="fa fa-envelope"></i> <span class="label label-success">4</span>
					</a>
						<ul class="dropdown-menu">
							<li class="header">You have 4 messages</li>
							<li>
								<!-- inner menu: contains the actual data -->
								<ul class="menu">
									<li>
										<!-- start message --> <a href="#">
											<div class="pull-left">
												<img src="/img/avatar3.png" class="img-circle"
													alt="User Image" />
											</div>
											<h4>
												Support Team <small><i class="fa fa-clock-o"></i> 5 mins</small>
											</h4>
											<p>Why not buy a new awesome theme?</p>
									</a>
									</li>
									<!-- end message -->
									<li><a href="#">
											<div class="pull-left">
												<img src="/img/avatar2.png" class="img-circle"
													alt="user image" />
											</div>
											<h4>
												AdminLTE Design Team <small><i class="fa fa-clock-o"></i> 2
													hours</small>
											</h4>
											<p>Why not buy a new awesome theme?</p>
									</a></li>
									<li><a href="#">
											<div class="pull-left">
												<img src="/img/avatar.png" class="img-circle"
													alt="user image" />
											</div>
											<h4>
												Developers <small><i class="fa fa-clock-o"></i> Today</small>
											</h4>
											<p>Why not buy a new awesome theme?</p>
									</a></li>
									<li><a href="#">
											<div class="pull-left">
												<img src="/img/avatar2.png" class="img-circle"
													alt="user image" />
											</div>
											<h4>
												Sales Department <small><i class="fa fa-clock-o"></i>
													Yesterday</small>
											</h4>
											<p>Why not buy a new awesome theme?</p>
									</a></li>
									<li><a href="#">
											<div class="pull-left">
												<img src="/img/avatar.png" class="img-circle"
													alt="user image" />
											</div>
											<h4>
												Reviewers <small><i class="fa fa-clock-o"></i> 2 days</small>
											</h4>
											<p>Why not buy a new awesome theme?</p>
									</a></li>
								</ul>
							</li>
							<li class="footer"><a href="#">See All Messages</a></li>
						</ul></li>
					<!-- Notifications: style can be found in dropdown.less -->
					<li class="dropdown notifications-menu"><a href="#"
						class="dropdown-toggle" data-toggle="dropdown"> <i
							class="fa fa-warning"></i> <span class="label label-warning">10</span>
					</a>
						<ul class="dropdown-menu">
							<li class="header">You have 10 notifications</li>
							<li>
								<!-- inner menu: contains the actual data -->
								<ul class="menu">
									<li><a href="#"> <i class="ion ion-ios7-people info"></i> 5 new
											members joined today
									</a></li>
									<li><a href="#"> <i class="fa fa-warning danger"></i> Very long
											description here that may not fit into the page and may cause
											design problems
									</a></li>
									<li><a href="#"> <i class="fa fa-users warning"></i> 5 new
											members joined
									</a></li>

									<li><a href="#"> <i class="ion ion-ios7-cart success"></i> 25
											sales made
									</a></li>
									<li><a href="#"> <i class="ion ion-ios7-person danger"></i> You
											changed your username
									</a></li>
								</ul>
							</li>
							<li class="footer"><a href="#">View all</a></li>
						</ul></li>

					<!-- Tasks: style can be found in dropdown.less -->
					<li class="dropdown tasks-menu"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown"> <i class="fa fa-tasks"></i> <span
							class="label label-danger">9</span>
					</a>
						<ul class="dropdown-menu">
							<li class="header">You have 9 tasks</li>
							<li>
								<!-- inner menu: contains the actual data -->
								<ul class="menu">
									<li>
										<!-- Task item --> <a href="#">
											<h3>
												Design some buttons <small class="pull-right">20%</small>
											</h3>
											<div class="progress xs">
												<div class="progress-bar progress-bar-aqua"
													style="width: 20%" role="progressbar" aria-valuenow="20"
													aria-valuemin="0" aria-valuemax="100">
													<span class="sr-only">20% Complete</span>
												</div>
											</div>
									</a>
									</li>
									<!-- end task item -->
									<li>
										<!-- Task item --> <a href="#">
											<h3>
												Create a nice theme <small class="pull-right">40%</small>
											</h3>
											<div class="progress xs">
												<div class="progress-bar progress-bar-green"
													style="width: 40%" role="progressbar" aria-valuenow="20"
													aria-valuemin="0" aria-valuemax="100">
													<span class="sr-only">40% Complete</span>
												</div>
											</div>
									</a>
									</li>
									<!-- end task item -->
									<li>
										<!-- Task item --> <a href="#">
											<h3>
												Some task I need to do <small class="pull-right">60%</small>
											</h3>
											<div class="progress xs">
												<div class="progress-bar progress-bar-red"
													style="width: 60%" role="progressbar" aria-valuenow="20"
													aria-valuemin="0" aria-valuemax="100">
													<span class="sr-only">60% Complete</span>
												</div>
											</div>
									</a>
									</li>
									<!-- end task item -->
									<li>
										<!-- Task item --> <a href="#">
											<h3>
												Make beautiful transitions <small class="pull-right">80%</small>
											</h3>
											<div class="progress xs">
												<div class="progress-bar progress-bar-yellow"
													style="width: 80%" role="progressbar" aria-valuenow="20"
													aria-valuemin="0" aria-valuemax="100">
													<span class="sr-only">80% Complete</span>
												</div>
											</div>
									</a>
									</li>
									<!-- end task item -->
								</ul>
							</li>
							<li class="footer"><a href="#">View all tasks</a></li>
						</ul></li>
					<!-- User Account: style can be found in dropdown.less -->
					<li class="dropdown user user-menu"><a href="#"
						class="dropdown-toggle" data-toggle="dropdown"> <i
							class="glyphicon glyphicon-user"></i> <span><?php echo $loggedInUser ?> <i
								class="caret"></i></span>
					</a>
						<ul class="dropdown-menu">
							<!-- User image -->
							<li class="user-header bg-light-blue"><img src="<?php echo $this->layout()->auth['profile_pic_url']?>"
								class="img-circle" alt="User Image" />
								<p>
									<?php echo $this->layout()->auth['firstname'].", ".$this->layout()->auth['lastname']?> <small>Member since <?php echo $this->layout()->auth['created']?></small>
								</p></li>
							<!-- Menu Body -->
			
							<!-- Menu Footer-->
							<li class="user-footer">
								<div class="pull-left">
									<a href="<?php echo $this->url("profile",array('action'=>'view'))?>"
										class="btn btn-default btn-flat">Profile</a>
								</div>
								<div class="pull-right">
                                        <a href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>"
										class="btn btn-default btn-flat">Sign out</a>
								</div>
							</li>
						</ul></li>
				</ul>
			</div>
		</nav>
	</header>
	<div class="wrapper row-offcanvas row-offcanvas-left">
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="left-side sidebar-offcanvas">
			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">
				<!-- Sidebar user panel -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="<?php echo $this->layout()->auth['profile_pic_url']?>" class="img-circle"
							alt="<?php echo  $loggedInUser?>"
							title="<?php echo  $loggedInUser?>" />
					</div>
					<div class="pull-left info">
						<p title="<?php echo  $loggedInUser?>"> Hello, <?php echo $this->layout()->auth['firstname']; ?></p>

						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>
				<!-- search form -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control"
							placeholder="Search..." /> <span class="input-group-btn">
							<button type='submit' name='seach' id='search-btn'
								class="btn btn-flat">
								<i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				<!-- sidebar menu: : style can be found in sidebar.less -->
				<ul class="sidebar-menu">
                    <?php 
                    

                    echo $this->navigation('navigation')
                    ->menu()
                    ->setPartial('partial/sidebar')
                    ->setAcl($this->layout()->acl)
                    ->setRole('guest')
                    ->render();
                                 
                    ?>
                    </ul>
			</section>
			<!-- /.sidebar -->
		</aside>


		<!-- Right side column. Contains the navbar and content of the page -->
		<aside class="right-side">
			<!-- Content Header (Page header) -->
	        <?php echo $this->navigation('navigation')->breadcrumbs()
                                                      ->setMinDepth(0)
                                                      ->setMaxDepth(2)
                                                      ->setPartial('partial/breadcrumb');
	        
	        
	        
            ?>

			<!-- Main content -->
			<section class="content">
			
			     <?php echo $this->content; ?>
			
			</section>
			<!-- /.content -->
		</aside>
		<!-- /.right-side -->
	</div>
	<!-- ./wrapper -->


	<!-- jQuery 2.0.2 -->
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
	<!-- jQuery UI 1.10.3 -->
	<script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<!-- Bootstrap -->
	<script src="/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- jvectormap -->
	<script src="/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"
		type="text/javascript"></script>
	<script src="/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"
		type="text/javascript"></script>
	<!-- jQuery Knob Chart -->
	<script src="/js/plugins/jqueryKnob/jquery.knob.js"
		type="text/javascript"></script>
	<!-- daterangepicker -->
	<script src="/js/plugins/daterangepicker/daterangepicker.js"
		type="text/javascript"></script>
	<!-- datepicker -->
	<script src="/js/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>

	<!-- iCheck -->
	<script src="/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
	
	<!-- InputMask -->
    <script src="/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        
	<!-- AdminLTE App -->
	<script src="/js/AdminLTE/app.js" type="text/javascript"></script>

	<!-- AdminLTE dashboard demo (This is only for demo purposes) 
	<script src="/js/AdminLTE/dashboard.js" type="text/javascript"></script>-->

	<!-- AdminLTE for demo purposes 
	<script src="/js/AdminLTE/demo.js" type="text/javascript"></script>-->
	
	<!-- Custon Js -->
   <script src="/js/custom.js" type="text/javascript"></script>
	

</body>
</html>