					<ul>

					<li><a href="<?php echo $this->url('profile',array('action'=>'upload-profile-picture')); ?>">Change Profile Picture</a></li>
					<li><a
						href="<?php echo $this->url('profile',array('action'=>'edit')); ?>">Edit
							Profile Details</a></li>
					<li><a
						href="<?php echo $this->url('profile',array('action'=>'settings')); ?>">Profile
							Settings</a></li>
					<li><a
						href="<?php echo $this->url('profile',array('action'=>'change-password')); ?>">Change
							Password</a></li>

					<li><a
						href="<?php echo $this->url('profile',array('action'=>'change-password')); ?>">Reset
							Password</a></li>
					<li><a
						href="<?php echo $this->url('login/process',array('action'=>'logout')); ?>">Logout</a></li>

				</ul>