<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">

	<section class="col-lg-5 connectedSortable">

		
			
				<!-- right navigation //-->
             <?php echo $this->render('layout/hr-menu-update-e') ?>
			
		
	</section>
	
	
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Clubs</div>
				<div class="panel-body">

					<div class="box-body">
					
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->



</div>