<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"> <a href="<?php echo $this->url('hr',array('action'=>'view-employee','id'=>$this->id))?>"><i class="fa fa-angle-double-left"></i></a> <?php echo $this->employeeData["firstname"];?>'s Salary</div>
				<div class="panel-body">

					<div class="box-body">
				
				
				<div class="row">
				
				           <div class="col-md-6">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <i class="fa fa-dollar"></i>
                                    <h3 class="box-title">Employee Salary</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <dl class="dl-horizontal">
                                       <dt>Current</dt>
                                       <?php 
                                       //computation logic
                                        $curr_sal = $this->employeeSalaryHistory['current'];
                                        $prev_sal = $this->employeeSalaryHistory['previous'];
                                        $increasement = $curr_sal - $prev_sal;
                                        $percent_inc =  ($increasement / $prev_sal ) * 100;
                                       
                                        ?>
                                        <dd><?php echo $curr_sal?></dd>
                                        <dt>Last Raise Date:</dt>
                                        <dd><?php echo date("M d, Y", strtotime($this->employeeSalaryHistory['last_race_date'])); ?></dd>
                                        <dt>Last Raise Amount:</dt>
                                        <dd><?php echo $prev_sal;?></dd>
                                        <dt>percentage:</dt>
                                        <dd><?php echo money_format('%i',$percent_inc)." %";?></dd>
                                       
                                    </dl>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div><!-- ./col -->
                        
                        
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Salary Updates History</h3>
                                    <div class="box-tools">
                                        <div class="input-group">
                                            <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"/>
                                            <div class="input-group-btn">
                                                <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive no-padding">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Date</th>
                                            <th>Ammount</th>
                                            <th>Options</th>
                                        </tr>
                                        <?php 
                                        /*computation of raised and Percentage ammount here*/
                                        $ctr= 0;
                                        ?>
                                       <?php foreach ($this->employeeSalary as $sal):?>
                                       <?php $ctr ++;?>
                                        <tr>
                                            <td><?php echo date("m/d/y", strtotime($sal->created));?></td>
                                            <td><?php echo money_format('%i', $sal->salary); ?></td>
                                            <td><?php 
                                            if(  $ctr <= 1){
                                              echo "Change";	
                                            }
                                            ?></td>
                                        </tr>
                                      <?php endforeach;?>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
				<div class="panel-body rightbar-menu">
			<!-- right navigation //-->
          <?php  echo $this->render('layout/hr-menu-update-e') ?>
		</div>
		</div>
	</section>

</div>