<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		
			
				<!-- right navigation //-->
             <?php echo $this->render('layout/hr-menu-update-e') ?>
			
		
	</section>
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Points</div>
				<div class="panel-body">

					<div class="box-body">
					
					<section style="float:left; border:1px solid red">
					
					Positive Feedback
					
					</section>
					
					<section style="float:left; border:1px solid red">
					
					Negative Feedback
					
					</section>
					
					
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->


</div>