<?php echo $this->render('flashmessenger/layout');
$files= $this->empMemos;
$addForm = $this->addFileForm;

var_dump($files);

 ?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><a href="<?php echo $this->url('hr',array('action'=>'view-employee','id'=>$this->employeeData["users_id"]))?>"><i class="fa fa-angle-double-left"></i></a> <?php echo $this->employeeData["firstname"];?>'s Memo</div>
				<div class="panel-body">

					<div class="box-body">


						<div class="box">


							<div class="box-header">
								<h3 class="box-title">
									<i class="fa fa-calendar"></i> Memo Files Received
								</h3>

							</div>
							<!-- /.box-header -->
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover">
									<tbody>
										<tr>
											
											<th>Title</th>
											<th>Date Filed</th>
											<th>File</th>
											<th>Options</th>
											
										</tr>
                                       
                                        <tr>
										  <td>Tardiness 1st Warning</td>
										  <td>7/7/14</td>
										    <td>userMemo_1_458854sd87sds8sds.docx</td>
										  <td><a ref="#" title="delete this memo"><i class="fa fa-times"></i></a></td>
										</tr>
								

									</tbody>
								</table>
								
														<?php
// // add at the end of the file after the table
// echo $this->paginationControl (
// 		// the paginator object
// 		$files,
// 		// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
// 		'Jumping',
// 		// the partial to use to render the control
// 		array (
// 				'partial/paginator.phtml',
// 				'Hr'
// 		),
// 		// the route to link to when a user clicks a control link
// 		array (
// 				'route' => 'paginator',
// 		) );

                         ?>
							</div>
							<!-- /.box-body -->
						</div>

					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">201 Files Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
                      <?php  echo $this->render('layout/hr-menu-update-e') ?>
		</div>
		</div>
	</section>

</div>
