<?php echo $this->render('flashmessenger/layout');
$files= $this->empFiles;
$addForm = $this->addFileForm;
 ?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->employeeData["firstname"];?>'s 201 Files</div>
				<div class="panel-body">

					<div class="box-body">


						<div class="box">


							<div class="box-header">
								<h3 class="box-title">
									<i class="fa fa-paperclip"></i> 201 Files Completed
								</h3>

							</div>
							<!-- /.box-header -->
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover">
									<tbody>
										<tr>
											<th>Type</th>
											<th>Date Added</th>
											<th>File</th>
											<th>Description</th>
											<th>Options</th>

										</tr>
                                        <?php foreach ($files as $f):?>
                                        <tr>
											<td><?php echo $f->file_type; ?></td>
											<td><?php echo date("m/d/y g:i A", strtotime($f->added)); ?></td>
											<td><i class="fa  fa-file-o"></i><?php echo $f->filename; ?></td>
											<td><?php echo $f->description; ?></td>
											<td>
												<a  title ="download this file" href="<?php echo  $this->url('hr',array('action'=>'download-employee-file',
												                                            'id'=>$f->id,
												                                            'emp_id'=>$f->employee_id));?>""><i class="fa fa-cloud-download"></i></a> | 
												<a title ="delete this file" href="<?php echo  $this->url('hr',array('action'=>'delete-employee-file',
												                                            'id'=>$f->id,
												                                            'emp_id'=>$f->employee_id));?>"><i class="fa  fa-times-circle"></i></a> 
												
											</td>
										</tr>
										<?php endforeach;?>

									</tbody>
								</table>
								
														<?php
// // add at the end of the file after the table
// echo $this->paginationControl (
// 		// the paginator object
// 		$files,
// 		// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
// 		'Jumping',
// 		// the partial to use to render the control
// 		array (
// 				'partial/paginator.phtml',
// 				'Hr'
// 		),
// 		// the route to link to when a user clicks a control link
// 		array (
// 				'route' => 'paginator',
// 		) );

                         ?>
							</div>
							<!-- /.box-body -->
						</div>

					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">201 Files Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
                      <?php  echo $this->render('layout/hr-menu-update-e') ?>
		</div>
		</div>
	</section>

</div>
