<?php echo $this->render('flashmessenger/layout');
$attendance = $this->attendance;

 ?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"> <a href="<?php echo $this->url('hr',array('action'=>'view-employee','id'=>$this->employeeData["users_id"]))?>"><i class="fa fa-angle-double-left"></i></a> <?php echo $this->employeeData["firstname"];?>'s System Logs Complete Details</div>
				<div class="panel-body">

					<div class="box-body">


						<div class="box well">


							<div class="box-header">
								<h3 class="box-title">
									<i class="fa fa-paperclip"></i> Attendance 
								</h3>

							</div>
							<!-- /.box-header -->
							<div class="box-body table-responsive no-padding">
								<table class="table table-hover">
									<tbody>
										<tr>
											<th>Time Stamp</th>
											<th>in/out</th>
											<th>Ip Address</th>
											

										</tr>
                                        <?php foreach ($attendance as $a):?>
                                        <tr>
											<td><?php echo date("m/d/y g:i A", strtotime($a->time)); ?></td>
											<td><?php echo ($a->log_type)? "In":"Out"?></td>
											<td><?php echo $a->ip_address; ?></td>
										
										</tr>
										<?php endforeach;?>

									</tbody>
								</table>
								
														<?php
// // add at the end of the file after the table
// echo $this->paginationControl (
// 		// the paginator object
// 		$files,
// 		// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
// 		'Jumping',
// 		// the partial to use to render the control
// 		array (
// 				'partial/paginator.phtml',
// 				'Hr'
// 		),
// 		// the route to link to when a user clicks a control link
// 		array (
// 				'route' => 'paginator',
// 		) );

                         ?>
							</div>
							<!-- /.box-body -->
						</div>

					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">201 Files Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
                      <?php  echo $this->render('layout/hr-menu-update-e') ?>
		</div>
		</div>
	</section>

</div>
