<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading"><?php echo $this->escapeHtml("Employees"); ?></div>
				<div class="panel-body">
					<div class="box-body">
						<!-- Content here -->



						<!-- Content here:end -->
					</div>
				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Employee Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
               <?php echo $this->render('layout/hr-menu') ?>
			</div>
		</div>
	</section>
</div>

