<?php 
//var_dump($this->employee_data);
?>
<?php echo $this->render('flashmessenger/layout')?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Employee Complete Data</div>
				<div class="panel-body">

					<div class="box-body">

						<div class="well">
							<img src="<?php echo HOST.$this->employee_data['profile_pic_url']?>"
								alt="User Image" />
							<h3><?php echo $this->employee_data['firstname']." ".$this->employee_data['middle']." ".$this->employee_data['lastname']?></h3>
						</div>

                    <div class="row">
                                              
                        <div class="col-md-6">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <i class="fa  fa-credit-card"></i>
                                    <h3 class="box-title">Personal Imformation</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <dl>
                                        <dt>About</dt>
                                        <dd><?php echo $this->employee_data['about']?></dd>
                                      				<dt><?php echo $this->translate('Address')?>:</dt>
							<dd><?php echo $this->employee_data['address']?></dd>

							<dt><?php echo $this->translate('Landline')?>:</dt>
							<dd><?php echo $this->employee_data['landline']?></dd>

							<dt><?php echo $this->translate('Cellphone')?>:</dt>
							<dd><?php echo $this->employee_data['cellphone']?></dd>

							<dt><?php echo $this->translate('Joined Date')?>:</dt>
							<dd><?php echo $this->employee_data['created']?></dd>

							<dt><?php echo $this->translate('Last Update')?>:</dt>
							<dd><?php echo $this->employee_data['last_modified']?></dd>
                                      
                                    </dl>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div><!-- ./col -->
                        <div class="col-md-6">
                            <div class="box box-solid">
                                <div class="box-header">
                                    <i class="fa fa-suitcase"></i>
                                    <h3 class="box-title">Employment</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">
                                    <dl class="dl-horizontal">
                                       <dt>Current Position:</dt>
                                        <dd><?php echo $this->employeeLatestPosition['position_name']?></dd>
                                        <dt>Current Salary:</dt>
                                        <dd><?php echo $this->employeeSalaryHistory['current']?></dd>
                                        <dt>Last Raise Date:</dt>
                                        <dd><?php echo date("M d, Y", strtotime($this->employeeSalaryHistory['last_race_date'])); ?></dd>
                                          <dt>Last Raise Amount:</dt>
                                        <dd><?php echo $this->employeeSalaryHistory['previous']?></dd>
                                         <dt>Evaluation Due:</dt>
                                        <dd><?php echo date("M d, Y", strtotime($evaluationDue['evaluation_due'])); ?></dd>                                 <dt>Date Hired:</dt>
                                        <dd><?php echo date("M d, Y", strtotime($this->dateHired)); ?></dd>
                                          <dt>Years of Service:</dt>
                                        <dd><?php echo round($this->employee_data['years_of_service']);?></dd>
                                        
                                    </dl>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div><!-- ./col -->
                    </div><!-- /.row -->
                    
                    
                    
                             <div class="box well">
                             
                       
                                <div class="box-header">
                                    <h3 class="box-title"><i class="fa fa-paperclip"></i> 201 Files Completed</h3>
                              
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive no-padding">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Type</th>
                                            <th>Date Added</th>
                                            <th>File</th>
                                            <th>Description</th>
                                          
                                        </tr>
                                        
                                        <?php foreach ($this->employeeFiles as $efiles):?>
                                        <tr>
                                            <td><?php echo $efiles['file_type_name']?></td>
                                            <td><?php echo date("m/d/y g:i A", strtotime($efiles['added'])); ?></td>
                                            <td><i class="fa  fa-file-o"></i><?php echo $efiles['filename']?></td>
                                            <td><?php echo $efiles['description']?></td>
                                              
                                        </tr>
                                        <?php endforeach;?>
                                        
                
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            
                            
                            
                            
                             <div class="box well">
                             
                       
                                <div class="box-header">
                                    <h3 class="box-title"><i class="fa fa-calendar"></i> Memo Received</h3>
                              
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive no-padding">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Type</th>
                                            <th>Date Added</th>
                                            <th>File</th>
                                          
                                        </tr>
                                        
                                        <?php foreach ($this->employeeMemo as $ememo):?>
                                        <tr>
                                            <td><?php echo $ememo['title']?></td>
                                            <td><?php echo date("m/d/y g:i A", strtotime($ememo['issue_date'])); ?></td>
                                            <td><i class="fa  fa-file-o"></i><?php echo $ememo['filename']?></td>
                                              
                                        </tr>
                                        <?php endforeach;?>
                                        
                
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            
                            
                                                      
                            
                             <div class="box well">
                             
                       
                                <div class="box-header">
                                    <h3 class="box-title"><i class="fa fa-check-square"></i> Quiz</h3>
                              
                                </div><!-- /.box-header -->
                                <div class="box-body table-responsive no-padding">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>Type</th>
                                            <th>Date</th>
                                            <th>Score</th>
                                          
                                        </tr>
                                        
                                        <?php foreach ($this->employeeQuiz as $equiz):?>
                                        <tr>
                                            <td><?php echo $equiz['title']?></td>
                                            <td><?php echo date("m/d/y g:i A", strtotime($equiz['created'])); ?></td>
                                            <td><?php echo $equiz['score']?>
											
											<div class="progress xs">
												<div class="progress-bar <?php echo ($equiz['score'] > 75)? "progress-bar-green":"progress-bar-red" ?>"
													style="width: <?php echo $equiz['score'].'%'?>;"></div>
											</div>
                                            
                                            </td>
                                              
                                        </tr>
                                        <?php endforeach;?>
                                        
                
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                    
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
             <?php echo $this->render('layout/hr-menu-update-e') ?>
			</div>
		</div>
	</section>

</div>