<?php 
//var_dump($this->employee_data);
?>
<?php echo $this->render('flashmessenger/layout')?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Employee Complete Data</div>
				<div class="panel-body">

					<div class="box-body">

						<div class="well">
							<img src="<?php echo $this->employee_data['profile_pic_url']?>"
								alt="User Image" />
							<h3><?php echo $this->employee_data['firstname'].", ".$this->employee_data['lastname']."  ".$this->employee_data['middle']."."?></h3>
						</div>

						<dl class="dl-horizontal">
							<dt><?php echo $this->translate('Address')?>:</dt>
							<dd><?php echo $this->employee_data['address']?></dd>

							<dt><?php echo $this->translate('Landline')?>:</dt>
							<dd><?php echo $this->employee_data['landline']?></dd>

							<dt><?php echo $this->translate('Cellphone')?>:</dt>
							<dd><?php echo $this->employee_data['cellphone']?></dd>

							<dt><?php echo $this->translate('Joined Date')?>:</dt>
							<dd><?php echo $this->employee_data['created']?></dd>

							<dt><?php echo $this->translate('Last Update')?>:</dt>
							<dd><?php echo $this->employee_data['last_modified']?></dd>

							<dt></dt>
							<dd></dd>

							<dt><?php echo $this->translate('About')?>:</dt>
							<dd><?php echo $this->employee_data['about']?></dd>
						</dl>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
             <?php echo $this->render('layout/hr-menu-update-e') ?>
			</div>
		</div>
	</section>

</div>