<?php echo $this->render('flashmessenger/layout')?>
<div class="row">


	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Profile Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php //echo $this->render('layout/menu') ?>
			</div>
		</div>
	</section>
	
	
	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Profile</div>
				<div class="panel-body">

					<div class="box-body">

						<div class="well">
							<img src="<?php echo $this->profile['profile_pic_url']?>"
								alt="User Image" />
							<h3><?php echo $this->profile['firstname']." ".$this->profile['middle'].". ".$this->profile['lastname']?></h3>
						</div>

						<dl class="dl-horizontal">
							<dt><?php echo $this->translate('Address')?>:</dt>
							<dd><?php echo $this->profile['address']?></dd>

							<dt><?php echo $this->translate('Landline')?>:</dt>
							<dd><?php echo $this->profile['landline']?></dd>

							<dt><?php echo $this->translate('Cellphone')?>:</dt>
							<dd><?php echo $this->profile['cellphone']?></dd>

							<dt><?php echo $this->translate('Joined Date')?>:</dt>
							<dd><?php echo $this->profile['created']?></dd>

							<dt><?php echo $this->translate('Last Update')?>:</dt>
							<dd><?php echo $this->profile['last_modified']?></dd>

							<dt></dt>
							<dd></dd>

							<dt><?php echo $this->translate('About')?>:</dt>
							<dd><?php echo $this->profile['about']?></dd>
						</dl>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->


</div>