<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">

 <!-- Left col -->
 <section class="col-lg-7 connectedSortable"> 
 <div>
  <!-- main sub page content// -->
  
  
 
 </div>

 </section><!-- /.Left col -->


  <!-- right col (We are only adding the ID to make the widgets sortable)-->
 <section class="col-lg-5 connectedSortable"> 
  <div>
<!-- right navigation //-->
   <ul>
   
   <li><a href="#">link1</a></li>
   <li><a href="#">link2</a></li>
   <li><a href="#">link3</a></li>
   <li><a href="#">link4</a></li>
   <li><a href="#">link5</a></li>
   </ul>
   
  </div>
 </section>

</div>